language: c

notifications:
  email: false
  
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      compiler: gcc
    - os: linux
      dist: xenial
      sudo: required
      compiler: clang
    - os: osx
      compiler: gcc
    - os: osx
      compiler: clang

addons:
  apt:
    packages:
      - cmake-data
      - cmake

script:
  - mkdir build && cd build
  - cmake ..
  - make -j2 sdatxtract
