language: cpp

notifications:
  email: false
  
matrix:
  include:
    - os: linux
      dist: focal
      compiler: gcc
      addons:
          apt:
              packages:
                  - gcc-9
                  - g++-9
    - os: linux
      dist: focal
      compiler: clang
      addons:
          apt:
              packages:
                  - clang-10
                  - clang++-10
    - os: osx
      compiler: clang
      osx_image: xcode12

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake

script:
  - mkdir build && cd build
  - cmake ..
  - make -j2 sdatxtract
